### ISSUE TITLE
[1.12.1] Harder Farming - crash on dedicated server

### ISSUE THREAD

**Issue by cosmicdan** [Draco18s/ReasonableRealism#10]
Howdy, FYI:

````

[13:42:35] [Server thread/ERROR]: Encountered an unexpected exception
--
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
at com.draco18s.farming.entities.ai.EntityAIAging.func_75246_d(EntityAIAging.java:97) ~[EntityAIAging.class:?]
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2346) ~[vp.class:?]
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2166) ~[vp.class:?]
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
at net.minecraft.world.World.func_72866_a(World.java:1983) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833) ~[oo.class:?]
at net.minecraft.world.World.func_72870_g(World.java:1945) ~[amu.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1755) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
````

Using latest version from Curse.

Cheers!

**Comment by Draco18s** [comment]
I'll take a look, thanks!

**Comment by Draco18s** [comment]
And fixed. This was a problem of a method having changed from 1.10ish that became client-side-only (so it used to work and now doesn't). Updated the code to use a different method.

**Comment by cosmicdan** [comment]
Awesome :)

Unrelated, but you may be interested: There doesn't seem to be any mod for 1.12.1 that makes days longer. Tough As Nails is an awesome mod that adds seasons, ambient temperature thirst, and some other stuff, but it's day length setting is used to calculate it's season length and doesn't actually increase day length.

Would this be something you'd consider doing in your Reasonable Realism mods?

If not, no matter - it's a relatively simple ASM mod that I could do, when I get around to it.

**Comment by cosmicdan** [comment]
DISREGARD: PrimalCore and Stellar Sky can increase day length.
