### ISSUE TITLE
NPE in com.draco18s.farming.FarmingEventHandler.harvestGrass during World Generation

### ISSUE THREAD

**Issue by LemADEC** [Draco18s/ReasonableRealism#27]
As of Harderfarming-4.0.0d with prospects-1.0.6.a1, an NPE crash was observed while creating a single player world.
It might be an Prospects bug too, not sure.
https://paste.dimdev.org/ixojefarug.mccrash

See https://github.com/dizzyd/prospects/issues/10

**Comment by LemADEC** [comment]
Seems like an Harderfarming error in com.draco18s.farming.FarmingEventHandler.harvestGrass
```
[00:25:01] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception while updating neighbours
	at net.minecraft.world.World.neighborChanged(World.java:571) ~[amu.class:?]
	at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:494) ~[amu.class:?]
	at net.minecraft.world.World.notifyNeighborsRespectDebug(World.java:439) ~[amu.class:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380) ~[amu.class:?]
	at net.minecraft.world.World.setBlockState(World.java:360) ~[amu.class:?]
	at de.teamlapen.vampirism.items.ItemTent.placeAt(ItemTent.java:51) ~[ItemTent.class:?]
	at de.teamlapen.vampirism.world.gen.WorldGenHunterCamp.placeTent(WorldGenHunterCamp.java:159) ~[WorldGenHunterCamp.class:?]
	at de.teamlapen.vampirism.world.gen.WorldGenHunterCamp.generate(WorldGenHunterCamp.java:107) ~[WorldGenHunterCamp.class:?]
	at de.teamlapen.vampirism.world.gen.VampirismWorldGen.generateOverworld(VampirismWorldGen.java:52) ~[VampirismWorldGen.class:?]
	at de.teamlapen.vampirism.world.gen.VampirismWorldGen.generate(VampirismWorldGen.java:33) ~[VampirismWorldGen.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1018) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:988) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.world.World.getChunkFromChunkCoords(World.java:309) ~[amu.class:?]
	at net.minecraft.world.World.getChunkFromBlockCoords(World.java:304) ~[amu.class:?]
	at net.minecraft.world.World.getBlockState(World.java:910) ~[amu.class:?]
	at thaumcraft.common.lib.utils.Utils.isWoodLog(Utils.java:179) ~[Utils.class:?]
	at thaumcraft.common.world.biomes.BiomeGenMagicalForest.isBlockAdjacentToWood(BiomeGenMagicalForest.java:185) ~[BiomeGenMagicalForest.class:?]
	at thaumcraft.common.world.biomes.BiomeGenMagicalForest.decorate(BiomeGenMagicalForest.java:171) ~[BiomeGenMagicalForest.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.populate(LostCityChunkGenerator.java:581) ~[LostCityChunkGenerator.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1017) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:988) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.world.World.getChunkFromChunkCoords(World.java:309) ~[amu.class:?]
	at net.minecraft.world.World.getChunkFromBlockCoords(World.java:304) ~[amu.class:?]
	at net.minecraft.world.World.getBlockState(World.java:910) ~[amu.class:?]
	at thaumcraft.common.lib.utils.Utils.isWoodLog(Utils.java:179) ~[Utils.class:?]
	at thaumcraft.common.world.biomes.BiomeGenMagicalForest.isBlockAdjacentToWood(BiomeGenMagicalForest.java:185) ~[BiomeGenMagicalForest.class:?]
	at thaumcraft.common.world.biomes.BiomeGenMagicalForest.decorate(BiomeGenMagicalForest.java:171) ~[BiomeGenMagicalForest.class:?]
	at mcjty.lostcities.dimensions.world.LostCityChunkGenerator.populate(LostCityChunkGenerator.java:581) ~[LostCityChunkGenerator.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1017) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.populate(Chunk.java:997) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:142) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.draco18s.farming.FarmingEventHandler.harvestGrass(FarmingEventHandler.java:645) ~[FarmingEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_706_FarmingEventHandler_harvestGrass_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:319) ~[ForgeEventFactory.class:?]
	at net.minecraft.block.Block.dropBlockAsItemWithChance(Block.java:572) ~[aow.class:?]
	at net.minecraft.block.Block.dropBlockAsItem(Block.java:564) ~[aow.class:?]
	at net.minecraft.block.BlockBush.checkAndDropBlock(BlockBush.java:67) ~[apc.class:?]
	at net.minecraft.block.BlockBush.neighborChanged(BlockBush.java:55) ~[apc.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.neighborChanged(BlockStateContainer.java:481) ~[awu$a.class:?]
	at net.minecraft.world.World.neighborChanged(World.java:550) ~[amu.class:?]
	... 38 more
```

**Comment by Draco18s** [comment]
Looks like the same issue as #23.
