### ISSUE TITLE
Console spam on first player join

### ISSUE THREAD

**Issue by LemADEC** [Draco18s/ReasonableRealism#28]
As of 1.12.1-Harderfarming-6.0.0a, a console spam is observed when first player join the server:
```
[17:06:07] [Server thread/INFO] [minecraft/DedicatedServer]: LemADEC joined the game
[17:06:07] [Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id minecraft:enchanter
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]: java.lang.ClassNotFoundException: toughasnails.season.SeasonASMHelper
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at java.lang.Class.forName0(Native Method)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at java.lang.Class.forName(Class.java:264)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at com.draco18s.farming.FarmingEventHandler.isTANInstalled(FarmingEventHandler.java:344)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at com.draco18s.farming.FarmingEventHandler.getTemperature(FarmingEventHandler.java:324)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at com.draco18s.farming.FarmingEventHandler.handleCrops(FarmingEventHandler.java:247)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at com.draco18s.farming.FarmingEventHandler.onCropGrow(FarmingEventHandler.java:197)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_540_FarmingEventHandler_onCropGrow_Pre.invoke(.dynamic)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraftforge.common.ForgeHooks.onCropsGrowPre(ForgeHooks.java:1281)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.block.BlockCrops.func_180650_b(BlockCrops.java:82)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.block.Block.func_180645_a(Block.java:508)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:307)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2163)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[17:06:08] [Server thread/INFO] [STDERR]: [com.draco18s.farming.FarmingEventHandler:isTANInstalled:349]:        at java.lang.Thread.run(Thread.java:748)
[17:06:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[17:06:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[17:06:08] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    ... 23 more
```

**Comment by Draco18s** [comment]
Its ignore-able.

I can remove the logging, but its not something that needs to be fixed in a hurry, it'll only display once.
