### ISSUE TITLE
NullPointerException when trying to insert sand into a non-container sluice from a hopper

### ISSUE THREAD

**Issue by nornagon** [Draco18s/ReasonableRealism#5]
MC version: 1.10.2
Harder Ores version: 1.1.0c

I placed a hopper pointing at a the first of two non-container sluices in a connected row and dropped a stack of sand into it, and the game immediately crashed with the following exception:

```
java.lang.NullPointerException: Ticking block entity
	at com.draco18s.ores.entities.TileEntityBasicSluice.getCapability(TileEntityBasicSluice.java:284)
	at com.draco18s.ores.entities.TileEntityBasicSluice.hasCapability(TileEntityBasicSluice.java:277)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:117)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:107)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:254)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:202)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:187)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

Full log here: http://paste.ee/p/ccn7k

**Comment by Draco18s** [comment]
I'll take a look here this evening if I can. Tomorrow if I can't.

**Comment by nornagon** [comment]
Thanks! Let me know if there's any further information I can provide.

**Comment by Draco18s** [comment]
Nope, the pasted crash is all I needed. Thanks.

**Comment by Draco18s** [comment]
Fixed for next build.

**Comment by nornagon** [comment]
Thanks!
